### ISSUE TITLE
ie 11 error

### ISSUE THREAD

**Issue by itdepartament** [johndatserakis/koa-vue-notes-api#1]
Hi. How can fix the problem with ie11, from windows 7? 
i have this string error "SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser."

**Comment by johndatserakis** [comment]
Unfortunately I don't have a windows computer to test on - but I found these threads that talk about this issue: [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjP1afjgoPWAhVJ7IMKHZQnB-cQFggoMAA&url=https%3A%2F%2Fgithub.com%2Fvuejs-templates%2Fwebpack%2Fissues%2F474&usg=AFQjCNGTGkUX1Lg5XjELo8WnhlMZ8Zc5Vw),
 [here](https://github.com/vuejs-templates/webpack/issues/260), and [here](https://laracasts.com/discuss/channels/vue/ie-11-vuex-polyfill)

I've gone ahead and added `import 'es6-promise/auto'` to the top of src/main.js on the master branch which should fix the issue. Let me know.

**Comment by itdepartament** [comment]
Big thank! now all worked correctly

2017-09-01 6:38 GMT+03:00 John Datserakis <notifications@github.com>:

**Comment by johndatserakis** [comment]
Awesome
