### ISSUE TITLE
p2 supports hot reload

### ISSUE THREAD

**Issue by giannisdag** [johndatserakis/koa-vue-notes-api#4]
Hi John, nice work you have here, I am just looking the same stuff and what you have done is very helpful, thank you. You should check that pm2 supports hot reload with watch, so there is no need to use noDaemon I think. I can send you an example.

**Comment by johndatserakis** [comment]
Thank you, glad it could help.

What I really like about using nodemon in development is that there really are like no settings - it does one thing and does it well. 

I find pm2 to be great in production, but I'd be hesitant to use it in development when nodemon is working perfectly and has given me no trouble. 

Thank you for the suggestion in any case. I will definitely look into it for the future.

**Comment by johndatserakis** [comment]
Thank you, closing for now
