### ISSUE TITLE
Issue Running on Windows 10

### ISSUE THREAD

**Issue by seand88** [johndatserakis/koa-vue-notes-api#5]
Trying to run this on windows 10, changed the watch in package.json to 

"watch": "SET NODE_ENV=development & nodemon app.js --exec",

This looks like it works but then I get an error.

`
> SET NODE_ENV=development & nodemon app.js --exec

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
 \api\src\index.js:3
import Koa from 'koa'
       ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[nodemon] app crashed - waiting for file changes before starting...
`

I dont know if its recognizing the import statement, im on latest version of Node.
What do I need to do to get this to run?

Thanks

**Comment by johndatserakis** [comment]
Looking into this. I don't have windows, but I'm going to test in a virtual machine.

In looking at the error, it's definitely something like babel not doing it's thing. `import` is still not fully supported in Node (without using .mjx) - so it's probably that babel is not converting the code.

There is one thing i'd like you to try before I go too far - can you first remove the `&` from your command? I'm sure you added it for some Windows reason, but I would say just try it without. Then, I'd like you to try it with `&&` instead of `&`.

**Comment by seand88** [comment]
Thanks for the reply.

Running without & does not issue the second command, so it doesn't try to execute app.js, it just sets the environment variable and quits.

Running with && produces the same error as with &

**Comment by seand88** [comment]
where is the app telling babel to convert the code so it can run with import? In the watch command there is no babel reference?

**Comment by johndatserakis** [comment]
Ok cool, got it. Yea in the `app.js`, `babel-register` is used in development on line 10.

Before the error, so somewhere in app.js, will you `console.log(process.env)` and let's see if you have `process.env.NODE_ENV` setting successfully.

**Comment by seand88** [comment]
I added this to the code in app.js

`require('babel-polyfill');
console.log(env);
if (env === 'development') {
    console.log('registering babel...');
    require('babel-register'); 
}`

Whats very strange is it logs our env as 'development' yet it doesnt log out the registering babel... statement.

**Comment by seand88** [comment]
Very strange running a length on the env variable returns 12 characters, while development only contains 11 characters... something weird is happening.

**Comment by seand88** [comment]
added a trim to this line to fix the issue... 
don't know if this is a windows specific thing or some kind of configuration setting at this point that causes it.

`const env = process.env.NODE_ENV.trim() || 'development';`

**Comment by seand88** [comment]
onto the next error.....


```
api\node_modules\knex\lib\index.js:49
  if (arguments.length === 0 || !config.client && !config.dialect) {
                                        ^
TypeError: Cannot read property 'client' of undefined
    at Knex (C:\extern\ShopifyFunnelPages\api\node_modules\knex\lib\index.js:49:41)
```

**Comment by johndatserakis** [comment]
Yup - something is up with your `process.env.NODE_ENV` setting in Windows. That's ok, you fixed it in one area, but that isn't going to fix it in all the other areas that rely on the variable (as you're finding out).

I have an idea though. I remember reading somewhere that there is a missing space when setting the `NODE_ENV` in windows. That's inline with what you're experiencing.

So, what someone mentioned to do was to eliminate the space in the actual call, so try and update your `watch` to this: `SET NODE_ENV=development&& nodemon app.js --exec`.

In that way, it actually gets rid of the extra space. If that doesn't work, you can try the `cross-env` library - it was made to help with this exact issue.

**Comment by seand88** [comment]
Awesome, doing the `SET NODE_ENV=development&& nodemon app.js --exec` works great.

**Comment by johndatserakis** [comment]
No problem glad you got it going
