### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by hidayatulfakhri** [johndatserakis/koa-vue-notes-api#6]
so i am a windows 10 user, and i really new to use docker, and i use sqlyog for sequel pro replacement, so i had this problem , 
 [nodemon] 1.17.5
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node app.js`
[0] [nodemon] restarting due to changes...
[0] [nodemon] starting `node app.js`
[1] > Starting dev server...
[0] Server running at 4000
[0] Running in development v2.0.0
[0] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[0] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[0] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

i know that related with docker, but i dont understand to use it, can you help me? 
anyway i miss it too:  "development environment, koa_vue_notes_development and koa_vue_notes_testing. In your production environment you would just have koa_vue_notes_production"
that s your read.me text about db, im dont understand what must i made and where , sorry for my bad programming skill . can you help me?

**Comment by johndatserakis** [comment]
Ok bud I got you let's figure this out.

First, this looks like an issue with your local redis setup. I think you have already run `docker-compose up -d --build`, right? 

Right now I believe there's a bug in the code that has the ratelimiter use the local redis instance instead of the docker container like it should.

So, the first thing I would do if I were you is to **get redis installed locally on your Windows computer**. Once you have that installed and running you should be able to enter `redis-cli ping` into a terminal and get `PONG` back.

Try that and let me know.

**Comment by hidayatulfakhri** [comment]
and another quiestion sir where i put this? 
host: 127.0.0.1, port: 3360, user: root, and password: docker

**Comment by johndatserakis** [comment]
Hmm, that is strange. What I would advise is to not use the [koa-vue-project](https://github.com/johndatserakis/koa-vue-notes-project) right now - but just stick to the [api](https://github.com/johndatserakis/koa-vue-notes-api) and [frontend](https://github.com/johndatserakis/koa-vue-notes-web) separately. I think that may be messing you up.

> host: 127.0.0.1, port: 3360, user: root, and password: docker
These are the credentials you need to set in you `.env` file, and you also use them to look at the database from whatever client you want.

You have made your `.env` file, right? It should look like this and be in your root:

```bash
APP_NAME = koa-vue-notes-api
APP_EMAIL = johndatserakis@gmail.com
APP_URL = https://koa-vue-notes-web.innermonkdesign.com

DB_HOST = 127.0.0.1
DB_PORT = 3306
DB_USER = root
DB_PASSWORD = docker
DB_DATABASE = koa_vue_notes

NODE_ENV = development
PORT = 4000

JWT_SECRET = wqefxfr1234fzqsfwfz24zfwezf
JWT_ACCESS_TOKEN_EXPIRATION_TIME = 1m

SENDGRID_API_KEY =

RECAPTCHA_SITEKEY =
RECAPTCHA_SITESECRET =
```

I think we are making progress because now the port is reporting as 3306 which means now it's just the database that won't connect. Let me know.

**Comment by hidayatulfakhri** [comment]
yeah ive seen that .env file, but i ve edit my last comment the error is not port 3306 anymore it change to 
[0] [2018-12-18T12:42:04.846] [INFO] development - OPTIONS /api/v1/user/signup RESPONSE: 204
[0] [2018-12-18T12:42:04.970] [INFO] development - { code: 'ER_ACCESS_DENIED_ERROR',
[0] errno: 1045,
[0] sqlMessage: 'Access denied for user ''@'172.18.0.1' (using password: NO)',
[0] sqlState: '28000',
[0] fatal: true,
[0] headers: { 'Access-Control-Allow-Origin': '*' },
[0] name: 'Error',
[0] message: 'ER_ACCESS_DENIED_ERROR: Access denied for user ''@'172.18.0.1' (using password: NO)',
[0] stack: 'Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'172.18.0.1' (using password: NO)\n at Handshake.Sequence._packetToErro 

so what happen here sir?

**Comment by hidayatulfakhri** [comment]
fyi i think it would be my kne error cause if i run knex : migrate latest this error show up
knex migrate:latest
C:\Users\ATUL\pisah\api\knexfile.js:3
if (!process.env.NODE_ENV) { throw new Error('NODE_ENV not set') }
                             ^

Error: NODE_ENV not set
    at Object.<anonymous> (C:\Users\ATUL\pisah\api\knexfile.js:3:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at tryLoadingDefaultConfiguration (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\bin\utils\cli-config-utils.js:32:12)
    at initKnex (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\bin\cli.js:54:27)
    at Command.commander.command.description.action (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\bin\cli.js:188:17)
    at Command.listener (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:654:12)
    at Command.parse (C:\Users\ATUL\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:474:21)

**Comment by hidayatulfakhri** [comment]
> Ahh ok so this is not good: `Error: NODE_ENV not set`. So it seems like your `NODE_ENV` is not setting correctly.
> 
> Make sure your migrate command looks like this: `NODE_ENV=development knex migrate:latest` - and because you're on Windows you may need to do this: `set NODE_ENV=development knex migrate:latest`.
> 
> Try that
 so i set it in package.json right? 
and here my package.json looks like
{
  "name": "koa-vue-notes-api",
  "version": "2.0.0",
  "description": "A SPA using Koa as the backend and Vue as the frontend.",
  "author": "John Datserakis",
  "private": true,
  "scripts": {
    "watch": "set NODE_ENV=development&& nodemon app.js --exec",
    "test": "set NODE_ENV=testing&& jest --forceExit",
    "build": "set NODE_ENV=production babel src -d build&& npm run pretty",
    "pretty": "prettier --write --print-width 80 --single-quote --trailing-comma es5 --tab-width 4 --no-semi 'src/**/*.js' 'tests/**/*.js'",
    "start-production": "set NODE_ENV=production pm2 start ecosystem.json",
    "clean": "npm cache clean --force"
  },
  "license": "MIT",
  "homepage": "https://github.com/johndatserakis/koa-vue-notes-api#readme",
  "dependencies": {
    "@sendgrid/mail": "6.2.1",
    "axios": "^0.18.0",
    "bcrypt": "^3.0.2",
    "date-fns": "^1.29.0",
    "dotenv": "^6.0.0",
    "faker": "^4.1.0",
    "fs-extra": "^6.0.1",
    "ioredis": "^3.2.2",
    "jest": "^23.1.0",
    "joi": "^13.4.0",
    "jsonwebtoken": "^8.2.2",
    "kcors": "^2.2.1",
    "knex": "^0.14.6",
    "koa": "^2.5.1",
    "koa-bodyparser": "^4.2.1",
    "koa-json-error": "^3.1.2",
    "koa-ratelimit": "^4.1.1",
    "koa-router": "^7.4.0",
    "koa-useragent": "^1.1.0",
    "log4js": "^3.0.6",
    "mysql": "^2.15.0",
    "npm": "^6.5.0",
    "pm2": "^2.10.4",
    "randexp": "^0.4.9"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-register": "^6.26.0",
    "nodemon": "^1.17.5",
    "prettier": "^1.13.4"
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions",
              "safari >= 7"
            ]
          }
        }
      ]
    ]
  },
  "keywords": [
    "koa",
    "koa2",
    "api",
    "boilerplate",
    "vue",
    "spa",
    "backend",
    "jwt",
    "pm2",
    "mysql",
    "database"
  ],
  "jest": {
    "testEnvironment": "node"
  }
}


after i running it the error still the same, everytime i try to sign up a new user this error show up:

[2018-12-19T08:30:44.478] [INFO] development - OPTIONS /api/v1/user/signup RESPONSE: 204
[2018-12-19T08:30:44.630] [INFO] development - { code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: 'Access denied for user \'\'@\'172.18.0.1\' (using password: NO)',
  sqlState: '28000',
  fatal: true,
  headers: { 'Access-Control-Allow-Origin': '*' },
  name: 'Error',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'\'@\'172.18.0.1\' (using password: NO)',
  stack: 'Error: ER_ACCESS_DENIED_ERROR: Access denied for user \'\'@\'172.18.0.1\' (using password: NO)\n

**Comment by johndatserakis** [comment]
What command are you running? I thought you said you were trying to do the migrations?

**Let's just focus on the migrations first.** That'll mean you have a good connection to the database, and then after we can working on the frontend.

Let's break down the steps to get the API setup, slowly. Please delete everything you have already done. I'm going to clone a fresh copy of this repo and do it here with you. Please use this repo. Below are my steps:

1. Duplicate the `example.env` file and rename it `.env`.
2. Set the `JWT_SECRET` in the `.env` to something random - I used `2z3r2rwerwerwerwerwe`.
3. Ran `docker-compose up -d --build` to start my docker in the root of my project.
4. Opened up my SequelPro App to view my database and make sure it's working. I use host: 127.0.0.1, port: 3360, user: root, and password: docker. Everything works fine.
5. In the root of my project I run `npm i`. This will install all dependencies.
6. Run `npm run watch` in the root of the project. The result should look something like this - that means the API is running.

```bash
Johns-MacBook-Pro:koa-vue-notes-api johndatserakis$ npm run watch

> koa-vue-notes-api@2.0.0 watch /Users/johndatserakis/Documents/Code/koa-vue-notes-api
> NODE_ENV=development nodemon app.js --exec

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Server running at 4000
Running in development v2.0.0
```

7. Finally, visit `http://localhost:4000/` in your browser, Postman, or Insomnia. You should see this message: `{"message":"Hi there. 2.0.0"}`. That means you're up and running.

Can you complete this steps successfully?

**Comment by hidayatulfakhri** [comment]
i complete it till step 7, but when i run the step 8 in cmd ive trying this command
1. NODE_ENV=development knex migrate:latest
if i use this the erroe comes up
C:\Users\ATUL\pisah\api>NODE_ENV=development knex migrate:latest
Using environment: development
Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'172.18.0.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\ATUL\pisah\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14) 


2.set NODE_ENV=development knex migrate:latest
if i use this nothing happen and there is no reply in my cmd

>Opened up my SequelPro App to view my database and make sure it's working. I use host: 127.0.0.1, port: 3360, user: root, and password: docker. Everything works fine.
so i use here sqlyog, and ive set all element sam with you except port, cause if i use port 3360 i cant connect so i use port 3306
![screenshot 26](https://user-images.githubusercontent.com/45059523/50195990-f6e78080-0373-11e9-92fe-7dd9cd5e8302.png)

**Comment by johndatserakis** [comment]
Ok great - I'm sure we're close.

When you visit `http://localhost:4000/` in your browser what does it show.

**Comment by hidayatulfakhri** [comment]
{"message":"Hi there. 2.0.0"}
it show, and in the cmd showing
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Server running at 4000
Running in development v2.0.0
[2018-12-19T09:43:15.743] [INFO] development - GET / RESPONSE: 200
[2018-12-19T09:43:15.849] [INFO] development - { message: 'Not Found',
  name: 'NotFoundError',
  stack: 'NotFoundError: Not Found\n    at Object.throw (C:\\Users\\ATUL\\pisah\\api\\node_modules\\koa\\lib\\context.js:93:11)\n    at next.then (C:\\Users\\ATUL\\pisah\\api\\node_modules\\koa-json-error\\lib\\middleware.js:52:58)\n    at <anonymous>',
  status: 404 }
[2018-12-19T09:43:15.851] [INFO] development - GET /favicon.ico RESPONSE: 404

is thath okay?

**Comment by johndatserakis** [comment]
Ok yea - can you run this command to install `knex` globally `npm install knex -g`

**Comment by hidayatulfakhri** [comment]
ive install it, and this is coming from cmd 
Running in development v2.0.0
[2018-12-19T10:10:00.165] [INFO] development - GET / RESPONSE: 200
[2018-12-19T10:10:01.578] [INFO] development - GET / RESPONSE: 200

and by the way i cant remove the name of example.env, cause if its onli .env, the windows block it, so what i do before is,duplicate ang change the new one example.env to ..env

**Comment by johndatserakis** [comment]
Ok good - it looks like it's working better now.

But - **No** -  the file **has** to have the name of `.env`. So you need to do that.

**Comment by hidayatulfakhri** [comment]
> But - **No** - the file **has** to have the name of `.env`. So you need to do that.

![screenshot 27](https://user-images.githubusercontent.com/45059523/50196861-788cdd80-0377-11e9-93af-bc9e827cd280.png)
that happen when i delete the name file sir, so after i click ok the name not change

**Comment by hidayatulfakhri** [comment]
**OMG IT WORK, SIR** i dont even expect that the env file will make me so confuse like this :(

C:\Users\ATUL\pisah\api>NODE_ENV=development knex migrate:latest
Using environment: development
Batch 1 run: 3 migrations
C:\Users\ATUL\pisah\api\src\db\migrations\20170826111515_create_users_table.js
C:\Users\ATUL\pisah\api\src\db\migrations\20170826132549_create_refresh_token_table.js
C:\Users\ATUL\pisah\api\src\db\migrations\20170826132806_create_notes_table.js

C:\Users\ATUL\pisah\api>NODE_ENV=development knex seed:run
Using environment: development
Ran 2 seed files
C:\Users\ATUL\pisah\api\src\db\seeds\dev\seed_notes.js
C:\Users\ATUL\pisah\api\src\db\seeds\dev\seed_users.js

C:\Users\ATUL\pisah\api>

**Comment by hidayatulfakhri** [comment]
after this i only need to start the web right sir?

**Comment by johndatserakis** [comment]
Yup that should be it - great job. Now you should work on getting that front-end going.

First rule of programming - every line - every file - everything matters - or else it wouldn't be in the project!

**Comment by hidayatulfakhri** [comment]
**OMG THANK YOU SIIR,** sure yes sir, ill remember that. one again thank you sir
